#version 430

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;
layout(rgba16f, binding = 0) uniform image3D img_output;
layout(rgba16f, binding = 1) uniform image3D orbital;

uniform float occupation;

void main() {
	ivec3 pixel_coords = ivec3(gl_GlobalInvocationID.xyz);

	float previous = imageLoad(img_output, pixel_coords).r;
	float psi = imageLoad(orbital, pixel_coords).r;
	imageStore(img_output, pixel_coords, vec4(psi * psi * occupation + previous, 0.0, 0.0, 0.0));
}
